def swapFileData():
    file1=input('Give the name of the first file: ')
    file2=input('Give the name of the second file: ')
    openFile1=open(file1)
    data_a=openFile1.read()
    openFile2=open(file2)
    data_b=openFile2.read()
    openFile1ForWriting=open(file1,'w')
    openFile2ForWriting=open(file2,'w')
    openFile1ForWriting.write(data_b)
    openFile2ForWriting.write(data_a)
swapFileData()
